apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
spec:
  acme:
    email: wodhks1026@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http01-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: launchmywork-gateway
                namespace: platform-gateway
                kind: Gateway