# This means NGINX listens inside the container on port 80. server_name _; means it accepts any hostname. 

# root /usr/share/nginx/html; and index index.html; means it serves files from /usr/share/nginx/html, with index.html as the default page. 

# location / { try_files $uri $uri/ /index.html; } means it tries to serve the requested URI, and if not found, it serves index.html.

# location ~* \.(css|js|png|jpg|jpeg|gif|webp|svg|ico|pdf)$ { expires 7d; add_header Cache-Control "public"; try_files $uri =404; } means it sets caching headers for static assets and returns a 404 if the file is not found.


server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|webp|svg|ico|pdf)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}